### ISSUE TITLE
滴滴报错如下信息，是没有获取到相关元素吗？

### ISSUE THREAD

**Issue by AlterGu** [q7q7q7q7q7q7q7/ziyou#2]
```
★★当前福利金数量为：2
★★开始进行福利金签到！
今日福利金已签到，无需重复签到!
★★开始完成今日瓜分活动！
完成失败，可能昨日未报名！
★★开始报名明日瓜分活动！
今天已经报名参加瓜分明天的福利金了！
★★开始领取 周周领券 活动的优惠券
Traceback (most recent call last):
  File "/ql/data/scripts/q7q7q7q7q7q7q7_ziyou_main/滴滴.py", line 343, in <module>
    main(DIDI_JIFEN_TOKEN)
  File "/ql/data/scripts/q7q7q7q7q7q7q7_ziyou_main/滴滴.py", line 338, in main
    DiDi(ck).main()
  File "/ql/data/scripts/q7q7q7q7q7q7q7_ziyou_main/滴滴.py", line 318, in main
    self.receive_level_gift()
  File "/ql/data/scripts/q7q7q7q7q7q7q7_ziyou_main/滴滴.py", line 160, in receive_level_gift
    coupons_list = privileges.get('level_gift', {}).get('coupons', [])
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by q7q7q7q7q7q7q7** [comment]
有些账号没有这个权益，已更新新的判断条件，没有获取到会跳过该步骤
