### ISSUE TITLE
得物又有新的报错了，不知道是不是我环境的原因，烦请大佬解答一下

### ISSUE THREAD

**Issue by AfanChang** [q7q7q7q7q7q7q7/ziyou#6]
*****第1个账号*****
目标：迪士尼草莓熊（30cm）
剩余水滴：1770
种树进度: 12级 652/80000
★★开始签到
签到失败！ 网络拥堵
★★开始领取气泡水滴
明日10点可领,已经积攒340g水滴!
★★开始完成每日任务
开始任务：领40g水滴值
领取任务奖励失败! {'code': 403, 'status': 403, 'msg': '网络拥堵', 'error': True}
★★开始领取累计任务奖励
★★开始领取木桶水滴
★★开始多次执行浇水，领取浇水奖励
★★开始浇水充满气泡水滴
气泡水滴已充满，明日可领取340g
★★开始领取合种上线奖励
★★开始领取空中水滴
Traceback (most recent call last):
  File "/ql/data/scripts/raw_main_%E5%BE%97%E7%89%A9%E6%A3%AE%E6%9E%97.py", line 807, in <module>
    main(X_AUTH_TOKEN)
  File "/ql/data/scripts/raw_main_%E5%BE%97%E7%89%A9%E6%A3%AE%E6%9E%97.py", line 802, in main
    DeWu(ck, index).main()
  File "/ql/data/scripts/raw_main_%E5%BE%97%E7%89%A9%E6%A3%AE%E6%9E%97.py", line 764, in main
    self.receive_air_drop()
  File "/ql/data/scripts/raw_main_%E5%BE%97%E7%89%A9%E6%A3%AE%E6%9E%97.py", line 660, in receive_air_drop
    if response_dict.get('data').get('isOk') is True:
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by AfanChang** [comment]
已解决 未更新脚本导致
