### ISSUE TITLE
得物报错

### ISSUE THREAD

**Issue by wang-st** [q7q7q7q7q7q7q7/ziyou#9]
Traceback (most recent call last):
  File "/ql/data/scripts/dewu/dw.py", line 850, in <module>
    main(X_AUTH_TOKEN_LIST)
  File "/ql/data/scripts/dewu/dw.py", line 843, in main
    DeWu(ck, index).main()
  File "/ql/data/scripts/dewu/dw.py", line 810, in main
    self.help_user()
  File "/ql/data/scripts/dewu/dw.py", line 627, in help_user
    if any(re.match(pattern, invite_res) for pattern in ['助力成功', '助力失败，今日已助力过了']):
  File "/ql/data/scripts/dewu/dw.py", line 627, in <genexpr>
    if any(re.match(pattern, invite_res) for pattern in ['助力成功', '助力失败，今日已助力过了']):
  File "/usr/local/lib/python3.10/re.py", line 190, in match
    return _compile(pattern, flags).match(string)
TypeError: expected string or bytes-like object

**Comment by q7q7q7q7q7q7q7** [comment]
问题有复现吗？

**Comment by AfanChang** [comment]
> 更新了吗？问题有复现吗？

File "/ql/data/scripts/raw_main_得物森林.py", line 850, in <module>
    main(X_AUTH_TOKEN_LIST)
  File "/ql/data/scripts/raw_main_得物森林.py", line 840, in main
    SHARE_CODE_LIST.append(DeWu(ck, index).get_share_code())
  File "/ql/data/scripts/raw_main_得物森林.py", line 83, in __init__
    app_version = re.findall(r'duapp/([0-9]+\.[0-9]+\.[0-9]+)', USER_AGENT)[0]
IndexError: list index out of range
添加了sk和ua之后报如上错误

**Comment by ki11y0u** [comment]
Traceback (most recent call last):
  File "/ql/scripts/q7q7q7q7q7q7q7_ziyou/得物森林.py", line 851, in <module>
    main(X_AUTH_TOKEN_LIST)
  File "/ql/scripts/q7q7q7q7q7q7q7_ziyou/得物森林.py", line 845, in main
    DeWu(ck, index).main()
  File "/ql/scripts/q7q7q7q7q7q7q7_ziyou/得物森林.py", line 779, in main
    print(f'剩余水滴：{self.get_droplet_number()}')
  File "/ql/scripts/q7q7q7q7q7q7q7_ziyou/得物森林.py", line 244, in get_droplet_number
    droplet_number = response_dict.get('data').get('droplet')
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by q7q7q7q7q7q7q7** [comment]
> 

UA有问题 没有得物的版本号

**Comment by q7q7q7q7q7q7q7** [comment]
> > 更新了吗？问题有复现吗？
> 
> File "/ql/data/scripts/raw_main_得物森林.py", line 850, in main(X_AUTH_TOKEN_LIST) File "/ql/data/scripts/raw_main_得物森林.py", line 840, in main SHARE_CODE_LIST.append(DeWu(ck, index).get_share_code()) File "/ql/data/scripts/raw_main_得物森林.py", line 83, in **init** app_version = re.findall(r'duapp/([0-9]+.[0-9]+.[0-9]+)', USER_AGENT)[0] IndexError: list index out of range 添加了sk和ua之后报如上错误

UA有问题 没有得物的版本号，应该如一下，含有 duapp/5.24.5 的这种
Mozilla/5.0 (Linux; U; Android 10; zh-cn; Mi 10 Pro Build/QKQ1.191117.002) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/77.0.3865.120 MQQBrowser/11.0 Mobile Safari/537.36 COVC/045429 Mobile Safari/537.36/duapp/5.24.5(android;13)

**Comment by AfanChang** [comment]
> > > 更新了吗？问题有复现吗？
> > 
> > 
> > File "/ql/data/scripts/raw_main_得物森林.py", line 850, in main(X_AUTH_TOKEN_LIST) File "/ql/data/scripts/raw_main_得物森林.py", line 840, in main SHARE_CODE_LIST.append(DeWu(ck, index).get_share_code()) File "/ql/data/scripts/raw_main_得物森林.py", line 83, in **init** app_version = re.findall(r'duapp/([0-9]+.[0-9]+.[0-9]+)', USER_AGENT)[0] IndexError: list index out of range 添加了sk和ua之后报如上错误
> 
> UA有问题 没有得物的版本号，应该如一下，含有 duapp/5.24.5 的这种 Mozilla/5.0 (Linux; U; Android 10; zh-cn; Mi 10 Pro Build/QKQ1.191117.002) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/77.0.3865.120 MQQBrowser/11.0 Mobile Safari/537.36 COVC/045429 Mobile Safari/537.36/duapp/5.24.5(android;13)

已解决，感谢
